# Generated by Django 4.1 on 2022-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_remove_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='xxxx', max_length=15, unique=True),
        ),
    ]
