# Generated by Django 4.1 on 2022-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
