# Generated by Django 4.1 on 2022-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_alter_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=15),
        ),
    ]
